bookself:
  api:
    max-returned-books: 60
    max-returned-genres: 12
    max-returned-authors: 20
    max-popular-books-count: 100
    max-popular-books-by-genre-count: 10
    popularity-computation-cron-schedule: "0 7 * * * *"
  cors:
    allowed-origins: ${BOOKSELF_CORS_ALLOWED_ORIGINS:*}