bookself:
  api:
    max-returned-books: 24
    max-returned-genres: 12
    max-returned-authors: 20
    max-popular-books-count: 100
    max-popular-books-by-genre-count: 24
    popularity-cron-schedule: ${BOOKSELF_POPULARITY_CRON_SCHEDULE:0 0 0 * * *}
  cors:
    allowed-origins: ${BOOKSELF_CORS_ALLOWED_ORIGINS:*}