server:
  port: 8888
spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: username
    password: password
    driver-class-name: org.h2.Driver