name: Continuous Deployment

# Only deploy app when branch is merged into main
on:
  push:
    branches: [ main ]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew build -x test

    # TODO Deployment steps go here
