name: Continuous Integration

# Run CI whenever a PR is created against main
on:
  pull_request:
    branches: [ main ]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and verify coverage
      run: ./gradlew build --info jacocoTestReport
